version: "3.9"
services:
  ganache:
    restart: always
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
    command: ganache-cli -h 0.0.0.0 --port 8545 --mnemonic "concert ladder decline crumble mention because pepper address scan volco pulse pig"